name: Deploy to Render

on:
  push:
    branches:
      - main  # Adjust branch to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trigger Deploy Hook on Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "${RENDER_DEPLOY_HOOK}"